name: Docker

on:
  push:
    branches: '**'
    tags: '**'
  pull_request:
    branches:
      - 'master'
  schedule:
  - cron: 0 0 * * 6

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["5.6", "7.0", "7.1", "7.2", "7.4", "8.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images:
            dock4yii/php-fpm
          flavor: |
            suffix=-${{ matrix.php_version }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=tag
            type=ref,event=branch            
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: ${{ (github.repository == 'dock4yii/php-fpm') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/php-fpm${{ matrix.php_version }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: ${{ (github.repository == 'dock4yii/php-fpm') }}
          tags: ${{ steps.meta.outputs.tags }}
